#all tags 
#[ "MANAGE_SERVER_PLAYERCAP",  "SETTING_VOICE_CHAT",  "PLAYER_INFO",  "PLAYER_INFO_IP",  "MANAGE_SERVER_FPS",
#  "ADMIN_BYPASS_PLAYER_LIMIT",  "ADMIN_BYPASS_WHITE_LIST",  "PLAYER_JOB_BAN",  "EDIT_PLAYER", 
#  "MANAGE_SERVER_PASSWORD",  "MANAGE_SERVER_OOCMUTE",  "MANAGE_ROUND_3D",  "MANAGE_ROUND_NEXT_GAMEMODE",
#  "MANAGE_ROUND_GAME_EVENT",  "MANAGE_ROUND_START",  "MANAGE_ROUND_END",  "MANAGE_ROUND_NEXT_MAP", 
#  "MANAGE_ROUND_NEXT_AWAY_SITE",  "MANAGE_ROUND_ALERT_LEVEL",  "MANAGE_ROUND_CALL_SHUTTLE",  "MANAGE_ROUND_RECALL_SHUTTLE", 
#  "MANAGE_ROUND_CENTCOMM_ANNOUNCEMENT",  "MANAGE_ROUND_CENTCOMM_REPORT",  "MANAGE_ROUND_BLOCK_SHUTTLE_CALL", 
#  "MANAGE_ROUND_BLOCK_SHUTTLE_RECALL", "MANAGE_ROUND_MK_DEATH_SQUAD",  "PLAYER_SMITE",  "PLAYER_HEAL", 
#  "PLAYER_OOC_Mute_T",  "PLAYER_SPAWN_ITEM",  "ADMIN_ADDRESSABLE_SOUND",  "ADMIN_ADDRESSABLE_SOUND_AT_POS",
#  "ADMIN_ADDRESSABLE_MUSIC",  "DEBUG_FRAME_PROFILE",  "DEBUG_FRAME_VIEW_PROFILE",  "DEBUG_FRAME_REMOVE_PROFILE",
#  "DEBUG_DO_MEMORY_PROFILE",  "ADMIN_GHOST_DROP_ITEM",  "ADMIN_SMASH",  "ADMIN_ADD_MENTOR",  "ADMIN_REMOVE_MENTOR", 
#  "ROUND_REMOVE_BOUNTY", "ROUND_MODIFY_BOUNTY",  "ROUND_GET_CARGO_STATS",  "ROUND_ADD_BOUNTY",  "ROUND_SET_CARGO_CREDITS",
#  "ROUND_SET_CARGO_STATUS",  "ROUND_RNG_CARGO_BOUNTIES",  "DEBUG_MAKE_HOTSPOT",  "ADMIN_OVERLAY_INFO",  
#"ADMIN_OPEN_DOORS", "ADMIN_TOGGLE_BOLTS",  "ADMIN_ELECTRIFIE_DOOR",  "ADMIN_TP",  "ADMIN_CHANGE_PUSHBLE",  "ROUND_EARLY_LAUNCH",  "ADMIN_PRESS_BUTTON",  
#"MAP_PLACE_TILE",  "MAP_REMOVE_TILE",  "MAP_COLOUR_TILE",  "DEBUG_DESTROY_LIGHTS",  "DEBUG_SELF_SUFFICIENT",  "DEBUG_EMERGENCY_LIGHTS",  
#"VARIABLE_VIEWER",  "VV_EDIT",  "VV_CALL",  "PLAYER_MOVE",  "MAP_RENAME",  "MANAGE_GHOST_ROLES",  
#"ADMIN_INVENTORY_TRANSFER",  "PLAYER_AHELP",  "ADMIN_CHAT",  "MAP_TAG",  "PLAYER_MOVE_ALL",  "MANAGE_ANTAGONISTS",  "PLAYER_KICK",  
#"PLAYER_BAN",  "MAP_LINK",  "MAP_MOVE",  "ROUND_LAVALAND",  "MENTOR_MESSAGE",  
#"ADMIN_INFO",  "MAP_LOAD",  "MAP_ROTATE",  "PLAYER_PRAYER",  
#"MAP_CLONE",  "MAP_DESTROY",  "MAP_SPAWN",  "MAP_SAVE",  
#"ROUND_RANDOM_EVENTS",  "PLAYER_RESPAWN",  "PLAYER_GET_JOB_BANS",  "ADMIN_GHOST_INVENTORY",  "DEBUG_ADD_FAITH_POINTS",  
#"RCON_ACCESS",  "ADMIN_VOTE_VETO",  "ADMIN_LOGS",  "OFFLINE_MODE_MULTIKEY",  "OBJECT_INFO",  "ADMIN_BYPASS_GLOBAL_OOC_MUTE",  "ADMIN_CHAT_HTML","ADMIN_POSSESS_BODY",  
#"ADMIN_AGHOST",  "ADMIN_RESPAWN_SELF",  "MAP_CAMERA_OPTIONS" ] 

[ranks.host]
show_in_chat = false
abbreviation = "H"
color = "red"
permissions = ["*"]
#Admin basically everything except sensitive server credentials like login to hub
[ranks.admin]
show_in_chat = true
abbreviation = "A"
color = "red"
permissions = ["ADMIN_ADDRESSABLE_MUSIC", "ADMIN_ADDRESSABLE_SOUND", "ADMIN_ADDRESSABLE_SOUND_AT_POS",
 "ADMIN_ADD_MENTOR", "ADMIN_BYPASS_PLAYER_LIMIT", "ADMIN_BYPASS_WHITE_LIST", "ADMIN_CHANGE_PUSHBLE",
 "ADMIN_CHAT", "ADMIN_ELECTRIFIE_DOOR", "ADMIN_GHOST_DROP_ITEM", "ADMIN_GHOST_INVENTORY", "ADMIN_INFO", 
 "ADMIN_INVENTORY_TRANSFER", "ADMIN_OPEN_DOORS", "ADMIN_OVERLAY_INFO", "ADMIN_PRESS_BUTTON", 
 "ADMIN_REMOVE_MENTOR", "ADMIN_SMASH", "ADMIN_TOGGLE_BOLTS", "ADMIN_TP", "DEBUG_ADD_FAITH_POINTS",
 "DEBUG_DESTROY_LIGHTS", "DEBUG_EMERGENCY_LIGHTS", "DEBUG_MAKE_HOTSPOT", "DEBUG_SELF_SUFFICIENT",
 "EDIT_PLAYER", "MANAGE_ANTAGONISTS", "MANAGE_GHOST_ROLES", "MANAGE_ROUND_3D", "MANAGE_ROUND_ALERT_LEVEL",
 "MANAGE_ROUND_BLOCK_SHUTTLE_CALL", "MANAGE_ROUND_BLOCK_SHUTTLE_RECALL", "MANAGE_ROUND_CALL_SHUTTLE",
 "MANAGE_ROUND_CENTCOMM_ANNOUNCEMENT", "MANAGE_ROUND_CENTCOMM_REPORT", "MANAGE_ROUND_END", "MANAGE_ROUND_GAME_EVENT"
 , "MANAGE_ROUND_MK_DEATH_SQUAD", "MANAGE_ROUND_NEXT_AWAY_SITE", "MANAGE_ROUND_NEXT_GAMEMODE", "MANAGE_ROUND_NEXT_MAP",
 "MANAGE_ROUND_RECALL_SHUTTLE", "MANAGE_ROUND_START", "MANAGE_SERVER_OOCMUTE", "MANAGE_SERVER_PASSWORD",
 "MANAGE_SERVER_PLAYERCAP", "MAP_CLONE", "MAP_COLOUR_TILE", "MAP_DESTROY", "MAP_LINK", "MAP_LOAD", "MAP_MOVE",
 "MAP_PLACE_TILE", "MAP_REMOVE_TILE", "MAP_RENAME", "MAP_ROTATE", "MAP_SAVE", "MAP_SPAWN", "MAP_TAG", "MENTOR_MESSAGE",
 "PLAYER_AHELP", "PLAYER_BAN", "PLAYER_GET_JOB_BANS", "PLAYER_HEAL", "PLAYER_INFO", "PLAYER_INFO_IP", "PLAYER_JOB_BAN",
 "PLAYER_KICK", "PLAYER_MOVE", "PLAYER_MOVE_ALL", "PLAYER_OOC_MUTE_T", "PLAYER_PRAYER", "PLAYER_RESPAWN", "PLAYER_SMITE",
 "PLAYER_SPAWN_ITEM", "ROUND_ADD_BOUNTY", "ROUND_EARLY_LAUNCH", "ROUND_GET_CARGO_STATS", "ROUND_LAVALAND", "ROUND_MODIFY_BOUNTY",
 "ROUND_RANDOM_EVENTS", "ROUND_REMOVE_BOUNTY", "ROUND_RNG_CARGO_BOUNTIES", "ROUND_SET_CARGO_CREDITS", "ROUND_SET_CARGO_STATUS",
 "SETTING_VOICE_CHAT", "VARIABLE_VIEWER", "VV_CALL", "VV_EDIT", "RCON_ACCESS", "ADMIN_VOTE_VETO", "ADMIN_LOGS", "OFFLINE_MODE_MULTIKEY",
 "OBJECT_INFO", "ADMIN_POSSESS_BODY", "ADMIN_AGHOST", "ADMIN_RESPAWN_SELF", "MAP_CAMERA_OPTIONS"]
 #developer everything needed for debugging no kicking or banning
[ranks.developer]
show_in_chat = false
abbreviation = "D"
color = "red"
permissions = ["ADMIN_ADDRESSABLE_MUSIC", "ADMIN_ADDRESSABLE_SOUND", "ADMIN_ADDRESSABLE_SOUND_AT_POS",
 "ADMIN_BYPASS_PLAYER_LIMIT", "ADMIN_BYPASS_WHITE_LIST", "ADMIN_CHANGE_PUSHBLE", "ADMIN_CHAT", 
 "ADMIN_ELECTRIFIE_DOOR", "ADMIN_GHOST_DROP_ITEM", "ADMIN_GHOST_INVENTORY", "ADMIN_INFO",
 "ADMIN_INVENTORY_TRANSFER", "ADMIN_OPEN_DOORS", "ADMIN_OVERLAY_INFO", "ADMIN_PRESS_BUTTON", 
 "ADMIN_REMOVE_MENTOR", "ADMIN_SMASH", "ADMIN_TOGGLE_BOLTS", "ADMIN_TP", "DEBUG_ADD_FAITH_POINTS",
 "DEBUG_DESTROY_LIGHTS", "DEBUG_DO_MEMORY_PROFILE", "DEBUG_EMERGENCY_LIGHTS", "DEBUG_FRAME_PROFILE",
 "DEBUG_FRAME_REMOVE_PROFILE", "DEBUG_FRAME_VIEW_PROFILE", "DEBUG_MAKE_HOTSPOT", "DEBUG_SELF_SUFFICIENT",
 "EDIT_PLAYER", "MANAGE_ANTAGONISTS", "MANAGE_GHOST_ROLES", "MANAGE_ROUND_ALERT_LEVEL", "MANAGE_ROUND_BLOCK_SHUTTLE_CALL",
 "MANAGE_ROUND_BLOCK_SHUTTLE_RECALL", "MANAGE_ROUND_CALL_SHUTTLE", "MANAGE_ROUND_CENTCOMM_ANNOUNCEMENT",
 "MANAGE_ROUND_CENTCOMM_REPORT", "MANAGE_ROUND_END", "MANAGE_ROUND_GAME_EVENT", "MANAGE_ROUND_MK_DEATH_SQUAD",
 "MANAGE_ROUND_NEXT_AWAY_SITE", "MANAGE_ROUND_NEXT_GAMEMODE", "MANAGE_ROUND_NEXT_MAP", "MANAGE_ROUND_RECALL_SHUTTLE",
 "MANAGE_ROUND_START", "MAP_CLONE", "MAP_COLOUR_TILE", "MAP_DESTROY", "MAP_LINK", "MAP_LOAD", "MAP_MOVE", 
 "MAP_PLACE_TILE", "MAP_REMOVE_TILE", "MAP_RENAME", "MAP_ROTATE", "MAP_SAVE", "MAP_SPAWN", "MAP_TAG",
 "MENTOR_MESSAGE", "PLAYER_AHELP", "PLAYER_HEAL", "PLAYER_INFO", "PLAYER_MOVE", "PLAYER_MOVE_ALL", 
 "PLAYER_PRAYER", "PLAYER_RESPAWN", "PLAYER_SMITE", "PLAYER_SPAWN_ITEM", "RCON_ACCESS", "ROUND_ADD_BOUNTY",
 "ROUND_EARLY_LAUNCH", "ROUND_GET_CARGO_STATS", "ROUND_LAVALAND", "ROUND_MODIFY_BOUNTY", "ROUND_RANDOM_EVENTS",
 "ROUND_REMOVE_BOUNTY", "ROUND_RNG_CARGO_BOUNTIES", "ROUND_SET_CARGO_CREDITS", "ROUND_SET_CARGO_STATUS",
 "SETTING_VOICE_CHAT", "VARIABLE_VIEWER", "VV_CALL", "VV_EDIT", "ADMIN_VOTE_VETO", "ADMIN_LOGS", "OFFLINE_MODE_MULTIKEY",
 "OBJECT_INFO", "ADMIN_POSSESS_BODY", "ADMIN_AGHOST", "ADMIN_RESPAWN_SELF", "MAP_CAMERA_OPTIONS"]
 #Everything for allowing fun rounds , no player moderation
[ranks.game_master]
show_in_chat = false
abbreviation = "GM"
color = "red"
permissions = ["ADMIN_ADDRESSABLE_MUSIC", "ADMIN_ADDRESSABLE_SOUND", "ADMIN_ADDRESSABLE_SOUND_AT_POS",
 "ADMIN_ADD_MENTOR", "ADMIN_BYPASS_PLAYER_LIMIT", "ADMIN_BYPASS_WHITE_LIST", "ADMIN_CHANGE_PUSHBLE",
 "ADMIN_CHAT", "ADMIN_ELECTRIFIE_DOOR", "ADMIN_GHOST_DROP_ITEM", "ADMIN_GHOST_INVENTORY", "ADMIN_INFO",
 "ADMIN_INVENTORY_TRANSFER", "ADMIN_OPEN_DOORS", "ADMIN_OVERLAY_INFO", "ADMIN_PRESS_BUTTON", "ADMIN_REMOVE_MENTOR",
 "ADMIN_SMASH", "ADMIN_TOGGLE_BOLTS", "ADMIN_TP", "DEBUG_ADD_FAITH_POINTS", "DEBUG_DESTROY_LIGHTS",
 "DEBUG_EMERGENCY_LIGHTS", "DEBUG_MAKE_HOTSPOT", "DEBUG_SELF_SUFFICIENT", "EDIT_PLAYER", "MANAGE_ANTAGONISTS", 
 "MANAGE_GHOST_ROLES", "MANAGE_ROUND_3D", "MANAGE_ROUND_ALERT_LEVEL", "MANAGE_ROUND_BLOCK_SHUTTLE_CALL",
 "MANAGE_ROUND_BLOCK_SHUTTLE_RECALL", "MANAGE_ROUND_CALL_SHUTTLE", "MANAGE_ROUND_CENTCOMM_ANNOUNCEMENT",
 "MANAGE_ROUND_CENTCOMM_REPORT", "MANAGE_ROUND_END", "MANAGE_ROUND_GAME_EVENT", "MANAGE_ROUND_MK_DEATH_SQUAD",
 "MANAGE_ROUND_NEXT_AWAY_SITE", "MANAGE_ROUND_NEXT_GAMEMODE", "MANAGE_ROUND_NEXT_MAP", "MANAGE_ROUND_RECALL_SHUTTLE",
 "MANAGE_ROUND_START", "MAP_CLONE", "MAP_COLOUR_TILE", "MAP_DESTROY", "MAP_LINK", "MAP_LOAD", "MAP_MOVE", "MAP_PLACE_TILE"
 , "MAP_REMOVE_TILE", "MAP_RENAME", "MAP_ROTATE", "MAP_SAVE", "MAP_SPAWN", "MAP_TAG", "MENTOR_MESSAGE", "PLAYER_AHELP",
 "PLAYER_HEAL", "PLAYER_INFO", "PLAYER_MOVE", "PLAYER_MOVE_ALL", "PLAYER_OOC_MUTE_T", "PLAYER_PRAYER", "PLAYER_RESPAWN",
 "PLAYER_SMITE", "PLAYER_SPAWN_ITEM", "ROUND_ADD_BOUNTY", "ROUND_EARLY_LAUNCH", "ROUND_GET_CARGO_STATS", "ROUND_LAVALAND", 
 "ROUND_MODIFY_BOUNTY", "ROUND_RANDOM_EVENTS", "ROUND_REMOVE_BOUNTY", "ROUND_RNG_CARGO_BOUNTIES", "ROUND_SET_CARGO_CREDITS",
 "ROUND_SET_CARGO_STATUS", "SETTING_VOICE_CHAT", "VARIABLE_VIEWER", "VV_CALL", "VV_EDIT", "ADMIN_VOTE_VETO", "OBJECT_INFO",
 "ADMIN_POSSESS_BODY", "ADMIN_AGHOST", "ADMIN_RESPAWN_SELF", "MAP_CAMERA_OPTIONS"]
[ranks.mentor]
show_in_chat = true
abbreviation = "M"
color = "#6400ff"
permissions = ["MENTOR_MESSAGE", "PLAYER_INFO"]
[[players]]
identifier = "host_user_id"
rank = "host"
[[players]]
identifier = "admin_user_id"
rank = "admin"
[[players]]
identifier = "developer_user_id"
rank = "developer"
[[players]]
identifier = "game_master_user_id"
rank = "game_master"
[[players]]
identifier = "mentor_user_id"
rank = "mentor"
